apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "aurora-secret"
spec:
  externalSecretName: "aurora-secret"

  namespaceSelector:
    matchExpressions:
      - key: aurora-client
        operator: In
        values: ["true"]
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: rds
      kind: ClusterSecretStore
    refreshInterval: "1h"
    target:
      name: aurora-secret
      creationPolicy: 'Owner'
      template:
        type: Opaque
        data:
          application.yaml: |
            spring:
              datasource:
                base:
                  username: '{{ .username }}'
                  password: '{{ .password }}'
                  endpoints:
                    cluster:
                      writer: 'spring-aurora-failover.cluster-cjtkdvugsiy3.ap-northeast-1.rds.amazonaws.com'
                      reader: 'spring-aurora-failover.cluster-ro-cjtkdvugsiy3.ap-northeast-1.rds.amazonaws.com'
                    proxy:
                      writer: 'spring-aurora-failover-proxy.proxy-cjtkdvugsiy3.ap-northeast-1.rds.amazonaws.com'
                      reader: 'spring-aurora-failover-proxy-ro.endpoint.proxy-cjtkdvugsiy3.ap-northeast-1.rds.amazonaws.com'
    data:
      - secretKey: username
        remoteRef:
          key: 'arn:aws:secretsmanager:ap-northeast-1:129008548655:secret:rds!cluster-b68364ae-2efe-4e4f-a185-3bdb042830ad-uMiJMt'
          property: username
      - secretKey: password
        remoteRef:
          key: 'arn:aws:secretsmanager:ap-northeast-1:129008548655:secret:rds!cluster-b68364ae-2efe-4e4f-a185-3bdb042830ad-uMiJMt'
          property: password
