apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: rds
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
