apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: aurora-failover
  region: ap-northeast-1
  version: '1.29'
  tags:
    Purpose: AuroraFailover

iam:
  withOIDC: true
  serviceAccounts:
    # - metadata:
    #     name: apps
    #     namespace: default
    #   roleName: aurora-spring-failover-default-apps
    #   tags:
    #     Purpose: AuroraFailover
    - metadata:
        name: external-secrets
        namespace: external-secrets
      attachPolicy: {}
      roleName: aurora-spring-failover-eso
      tags:
        Purpose: AuroraFailover
    - metadata:
        name: report-uploader
        namespace: locust
      attachPolicy: {}
      roleName: aurora-spring-failover-report-uploader
      tags:
        Purpose: AuroraFailover

fargateProfiles:
  - name: fp-default
    selectors:
      - namespace: kube-system
      - namespace: default
      - namespace: external-secrets
      - namespace: locust
    tags:
      Purpose: AuroraFailover
