apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - locust-namespace.yaml
  - locust-master-deployment.yaml
  - locust-master-service.yaml
  - locust-worker-deployment.yaml

configMapGenerator:
  - name: locustfile
    namespace: locust
    files:
      - locustfile.py
