apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-master
  name: locust-master
  namespace: locust
spec:
  ports:
  - name: locust
    port: 5557
    protocol: TCP
    targetPort: locust
  - name: locust-ui
    port: 8089
    protocol: TCP
    targetPort: locust-ui
  selector:
    app: locust-master
  type: ClusterIP
