apiVersion: v1
kind: Service
metadata:
  name: locust-raw-direct-writer-master
  namespace: locust
spec:
  ports:
  - name: locust
    port: 5557
    protocol: TCP
    targetPort: locust
  selector:
    batch.kubernetes.io/job-name: locust-raw-direct-writer
    batch.kubernetes.io/job-completion-index: '0'
  type: ClusterIP
