apiVersion: batch/v1
kind: Job
metadata:
  name: locust-raw-direct-reader
  namespace: locust
spec:
  completions: 3
  completionMode: Indexed
  parallelism: 3
  template:
    spec:
      containers:
      - name: locust
        image: locustio/locust:2.29.1
        env:
        - name: JOB_CONTROLLER_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['batch.kubernetes.io/controller-uid']
        - name: DATA_SOURCE_HEADER_VALUE
          value: raw-direct
        - name: TARGET_DB_ROLE
          value: READER
        - name: LOCUST_EXPECT_WORKERS
          value: '2'
        - name: LOCUST_HOST
          value: 'http://standarddriver.default.svc.cluster.local:8080'
        - name: LOCUST_USERS
          value: '1000'
        - name: LOCUST_SPAWN_RATE
          value: '10'
        - name: LOCUST_RUN_TIME
          value: '1h'
        - name: LOCUST_STOP_TIMEOUT
          value: '5m'
        command:
        - bash
        - /home/locust/entrypoint.bash
        ports:
        - name: locust
          containerPort: 5557
        volumeMounts:
        - name: locustfile
          mountPath: /locustfiles/locustfile.py
          subPath: locustfile.py
        - name: entrypoint
          mountPath: /home/locust/entrypoint.bash
          subPath: entrypoint.bash
        - name: locustreport
          mountPath: /locustreports
      serviceAccountName: report-uploader
      restartPolicy: Never
      volumes:
      - name: locustfile
        configMap:
          name: locustfile
      - name: entrypoint
        configMap:
          name: entrypoint
      - name: locustreport
        emptyDir: {}
  backoffLimit: 0

