apiVersion: v1
kind: Service
metadata:
  name: standarddriver
  namespace: default
spec:
  selector:
    app: standarddriver
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: web
