apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

images:
  - name: 129008548655.dkr.ecr.ap-northeast-1.amazonaws.com/github.com/10hin/spring-aurora-failover/standarddriver:latest
    newTag: all-in-one
